CREATE TABLE EMPLOYEE (
  FirstName VARCHAR(25) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  CONSTRAINT EmployeeID INTEGER PRIMARY KEY NOT NULL,
  Gender CHAR(1),
  Education VARCHAR(20) NOT NULL,
  HireDate DATE NOT NULL,
  Review VARCHAR(11),
  Probation BOOL NOT NULL,
  Title VARCHAR(20) NOT NULL FOREIGN KEY,
  ManagerID INTEGER NOT NULL,
  RaisePercentage DECIMAL(4,2),
  CurrentSalary DECIMAL(8,2) NOT NULL
);